name: ci
on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs libudev-dev libx11-dev
    - name: Build Application
      run: |
        make setup && make all
    - name: Archive Application
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-latest
        path: target/release/conductor
  build-macos:
    runs-on: macos-latest
    env:
      CI: false
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Build Application
      run: |
        make setup && make all
    - name: Archive Application
      uses: actions/upload-artifact@v2
      with:
        name: macos-latest
        path: target/release/conductor
